spring:
  jpa:
    generate-ddl: true
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
logging:
  level:
    org.tinywind: TRACE
    org.springframework: INFO
    org.apache.velocity: INFO
    org.hibernate: INFO
    org.h2: INFO
  config: classpath:logback-spring.xml